language: go

go:
  - 1.9.x
  - tip

before_install:
  - go get -t -v ./...
  - go get -u github.com/haya14busa/goverage

script:
  - goverage -v -coverprofile=coverage.txt ./...

after_success:
  - bash <(curl -s https://codecov.io/bash)
