baseURL = "https://cavall.in/"
languageCode = "en-us"
title = "Luca Cavallin | Software Engineer"
theme = "PaperMod"
copyright = "Luca Cavallin"

enableRobotsTXT = true
buildDrafts = false
buildFuture = false
buildExpired = false
googleAnalytics = "G-LSCVVBZ6G3"
pygmentsUseClasses = true

[minify]
disableXML = true
minifyOutput = true

[params]
env = "production"
title = "Luca Cavallin"
description = '''
I am a software engineer at GitHub (Actions) and I am passionate about distributed systems and their application in the world
of developer- and infrastructure- tooling. I also enjoy contributing to open-source projects around Azure, Kubernetes,
and systems programming in general (e.g. container runtimes, networking...) using Go and Rust. Not long ago, I used to provide training and talks on Google Cloud and its certifications. In this blog, I write about
recent projects, interesting problems I've encountered, new knowledge I've acquired, and other random stuff.
'''
author = "Luca Cavallin"
images = ["/luca.png"]
keywords = ["Blog", "Portfolio"]
DateFormat = "2 January 2006"
ShowReadingTime = true
ShowShareButtons = true
ShowCodeCopyButtons = true
ShowFullTextinRSS = false
defaultTheme = "auto"
disableThemeToggle = false
disableSpecial1stPost = false
disableScrollToTop = false
disableAnchoredHeadings = false
hidemeta = false
hideSummary = false
showtoc = true
tocopen = true
ShowPostNavLinks = true
ShowBreadCrumbs = true
# ShareButtons
ShowWordCount = false
ShowRssButtonInSectionTermList = true
UseHugoToc = true
comments = true
hideFooter = false
# canonicalLinkText

[params.analytics.google]
SiteVerificationTag = "G-LSCVVBZ6G3"

[params.fuseOpts]
isCaseSensitive = false
shouldSort = true
location = 0
distance = 1_000
threshold = 0.4
minMatchCharLength = 0
keys = ["title", "permalink", "summary", "content"]

[[params.socialIcons]]
name = "linkedin"
url = "https://linkedin.com/in/lucavallin"

[[params.socialIcons]]
name = "github"
url = "https://github.com/lucavallin"

[params.label]
text = "Luca Cavallin"
icon = "/luca.png"
iconHeight = 35

[params.assets]
favicon = "/favicon.ico"
favicon16x16 = "/favicon-16x16.png"
favicon32x32 = "/favicon-32x32.png"
apple_touch_icon = "/apple-touch-icon.png"
safari_pinned_tab = "/favicon-32x32.png"
# disableHLJS = true

[params.cover]
hidden = true
hiddenInList = false
hiddenInSingle = false

[params.profileMode]
enabled = false
title = "Luca Cavallin"
subtitle = "Software Engineer"
imageUrl = "/luca.png"
imageWidth = 120
imageHeight = 120
imageTitle = "Luca Cavallin | Software Engineer"

[[params.profileMode.buttons]]
name = "Posts"
url = "posts"

[[params.profileMode.buttons]]
name = "Tags"
url = "tags"

[params.editPost]
URL = "https://github.com/lucavallin/lucavallin.github.io/tree/main/content"
Text = "Suggest Changes"
appendFilePath = true

[params.homeInfoParams]
Title = "👋 Hello!"
Content = ""

[[menu.main]]
identifier = "home"
name = "Home"
url = "/"
weight = 10

[[menu.main]]
identifier = "posts"
name = "Posts"
url = "/posts"
weight = 15

[[menu.main]]
identifier = "tags"
name = "Tags"
url = "/tags/"
weight = 20

[[menu.main]]
identifier = "talks"
name = "Talks"
url = "https://www.youtube.com/watch?v=enV5If6cR48&list=PL19lZM0b-h-8OE_cD-270piJgzXqCoxsk"
weight = 30

[[menu.main]]
identifier = "first-issue"
name = "First Issue"
url = "https://firstissue.dev/"
weight = 40

[[menu.main]]
identifier = "mentoring"
name = "Mentoring"
url = "https://mentorcruise.com/mentor/lucacavallin/"
weight = 50

[markup.highlight]
anchorLineNos = false
codeFences = true
guessSyntax = false
hl_Lines = ''
hl_inline = false
lineAnchors = ''
lineNoStart = 1
lineNos = false
lineNumbersInTable = true
noClasses = true
noHl = false
style = 'monokai'
tabWidth = 4

[markup.tableOfContents]
startLevel = 1
endLevel = 6
